/**
 * Port of {@code com.hazelcast.internal.serialization.impl.SerializationConstants}.
 *
 * WARNING: DON'T CHANGE VALUES!
 * WARNING: DON'T ADD ANY NEW CONSTANT SERIALIZER!
 */
export const SerializationConstants = {
    CONSTANT_TYPE_NULL: 0,
    CONSTANT_TYPE_PORTABLE: -1,
    CONSTANT_TYPE_DATA_SERIALIZABLE: -2,
    CONSTANT_TYPE_BYTE: -3,
    CONSTANT_TYPE_BOOLEAN: -4,
    CONSTANT_TYPE_CHAR: -5,
    CONSTANT_TYPE_SHORT: -6,
    CONSTANT_TYPE_INTEGER: -7,
    CONSTANT_TYPE_LONG: -8,
    CONSTANT_TYPE_FLOAT: -9,
    CONSTANT_TYPE_DOUBLE: -10,
    CONSTANT_TYPE_STRING: -11,
    CONSTANT_TYPE_BYTE_ARRAY: -12,
    CONSTANT_TYPE_BOOLEAN_ARRAY: -13,
    CONSTANT_TYPE_CHAR_ARRAY: -14,
    CONSTANT_TYPE_SHORT_ARRAY: -15,
    CONSTANT_TYPE_INTEGER_ARRAY: -16,
    CONSTANT_TYPE_LONG_ARRAY: -17,
    CONSTANT_TYPE_FLOAT_ARRAY: -18,
    CONSTANT_TYPE_DOUBLE_ARRAY: -19,
    CONSTANT_TYPE_STRING_ARRAY: -20,
    CONSTANT_TYPE_UUID: -21,
    CONSTANT_TYPE_SIMPLE_ENTRY: -22,
    CONSTANT_TYPE_SIMPLE_IMMUTABLE_ENTRY: -23,

    // DEFAULT SERIALIZERS
    JAVA_DEFAULT_TYPE_CLASS: -24,
    JAVA_DEFAULT_TYPE_DATE: -25,
    JAVA_DEFAULT_TYPE_BIG_INTEGER: -26,
    JAVA_DEFAULT_TYPE_BIG_DECIMAL: -27,
    JAVA_DEFAULT_TYPE_ARRAY: -28,
    JAVA_DEFAULT_TYPE_ARRAY_LIST: -29,
    JAVA_DEFAULT_TYPE_LINKED_LIST: -30,
    JAVA_DEFAULT_TYPE_COPY_ON_WRITE_ARRAY_LIST: -31,
    JAVA_DEFAULT_TYPE_HASH_MAP: -32,
    JAVA_DEFAULT_TYPE_CONCURRENT_SKIP_LIST_MAP: -33,
    JAVA_DEFAULT_TYPE_CONCURRENT_HASH_MAP: -34,
    JAVA_DEFAULT_TYPE_LINKED_HASH_MAP: -35,
    JAVA_DEFAULT_TYPE_TREE_MAP: -36,
    JAVA_DEFAULT_TYPE_HASH_SET: -37,
    JAVA_DEFAULT_TYPE_TREE_SET: -38,
    JAVA_DEFAULT_TYPE_LINKED_HASH_SET: -39,
    JAVA_DEFAULT_TYPE_COPY_ON_WRITE_ARRAY_SET: -40,
    JAVA_DEFAULT_TYPE_CONCURRENT_SKIP_LIST_SET: -41,
    JAVA_DEFAULT_TYPE_ARRAY_DEQUE: -42,
    JAVA_DEFAULT_TYPE_LINKED_BLOCKING_QUEUE: -43,
    JAVA_DEFAULT_TYPE_ARRAY_BLOCKING_QUEUE: -44,
    JAVA_DEFAULT_TYPE_PRIORITY_BLOCKING_QUEUE: -45,
    JAVA_DEFAULT_TYPE_DELAY_QUEUE: -46,
    JAVA_DEFAULT_TYPE_SYNCHRONOUS_QUEUE: -47,
    JAVA_DEFAULT_TYPE_LINKED_TRANSFER_QUEUE: -48,
    JAVA_DEFAULT_TYPE_PRIORITY_QUEUE: -49,
    JAVA_DEFAULT_TYPE_OPTIONAL: -50,
    JAVA_DEFAULT_TYPE_LOCALDATE: -51,
    JAVA_DEFAULT_TYPE_LOCALTIME: -52,
    JAVA_DEFAULT_TYPE_LOCALDATETIME: -53,
    JAVA_DEFAULT_TYPE_OFFSETDATETIME: -54,
    TYPE_COMPACT: -55,
    TYPE_COMPACT_WITH_SCHEMA: -56,

    CONSTANT_SERIALIZERS_LENGTH: 57,

    // JAVA SERIALIZATION
    JAVA_DEFAULT_TYPE_SERIALIZABLE: -100,
    JAVA_DEFAULT_TYPE_EXTERNALIZABLE: -101,
    JAVA_DEFAULT_BYTE_BUFFER: -102,

    // LANGUAGE SPECIFIC SERIALIZERS
    CSHARP_CLR_SERIALIZATION_TYPE: -110,
    PYTHON_PICKLE_SERIALIZATION_TYPE: -120,
    JAVASCRIPT_JSON_SERIALIZATION_TYPE: -130,
    GO_GOB_SERIALIZATION_TYPE: -140,

    // HIBERNATE SERIALIZERS
    HIBERNATE3_TYPE_HIBERNATE_CACHE_KEY: -200,
    HIBERNATE3_TYPE_HIBERNATE_CACHE_ENTRY: -201,
    HIBERNATE4_TYPE_HIBERNATE_CACHE_KEY: -202,
    HIBERNATE4_TYPE_HIBERNATE_CACHE_ENTRY: -203,
    HIBERNATE5_TYPE_HIBERNATE_CACHE_KEY: -204,
    HIBERNATE5_TYPE_HIBERNATE_CACHE_ENTRY: -205,
    HIBERNATE5_TYPE_HIBERNATE_NATURAL_ID_KEY: -206,

    // RESERVED FOR JET
    JET_SERIALIZER_FIRST: -300,
    JET_SERIALIZER_LAST: -399,
} as const;
