export enum MaxSizePolicy {
    PER_NODE = 'PER_NODE',
    PER_PARTITION = 'PER_PARTITION',
    USED_HEAP_PERCENTAGE = 'USED_HEAP_PERCENTAGE',
    USED_HEAP_SIZE = 'USED_HEAP_SIZE',
    FREE_HEAP_PERCENTAGE = 'FREE_HEAP_PERCENTAGE',
    FREE_HEAP_SIZE = 'FREE_HEAP_SIZE',
    ENTRY_COUNT = 'ENTRY_COUNT',
    USED_NATIVE_MEMORY_SIZE = 'USED_NATIVE_MEMORY_SIZE',
    USED_NATIVE_MEMORY_PERCENTAGE = 'USED_NATIVE_MEMORY_PERCENTAGE',
    FREE_NATIVE_MEMORY_SIZE = 'FREE_NATIVE_MEMORY_SIZE',
    FREE_NATIVE_MEMORY_PERCENTAGE = 'FREE_NATIVE_MEMORY_PERCENTAGE',
}
